/product/all:
  get:
    tags: [Product]
    summary: Get all products
    responses:
      '200':
        description: A Array of JSON Product
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Product'
      '500':
        description: Error message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandartErrorMessage'
/product:
  get:
    tags: [Product]
    summary: Get a product by query params

    parameters:
      - in: query
        name: id
        schema:
          type: string
      - in: query
        name: titleEN
        schema:
          type: string
      - in: query
        name: titleUA
        schema:
          type: string
      - in: query
        name: descriptionEN
        schema:
          type: string
      - in: query
        name: descriptionUA
        schema:
          type: string
      - in: query
        name: price
        schema:
          type: number
      - in: query
        name: stars
        schema:
          type: string
      - in: query
        name: image
        schema:
          type: string
      - in: query
        name: Type
        schema:
          type: array
          items:
            type: string
      - in: query
        name: Category
        schema:
          type: array
          items:
            type: string
      - in: query
        name: Producer
        schema:
          type: string
      - in: query
        name: novelty
        schema:
          type: boolean
      - in: query
        name: discount
        schema:
          type: boolean
      - in: query
        name: discountValue
        schema:
          type: number
      - in: query
        name: discountPreviousPrice
        schema:
          type: number
      - in: query
        name: creator
        schema:
          type: string

    responses:
      '200':
        description: A JSON Product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      '500':
        description: Error message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandartErrorMessage'
  post:
    tags: [Product]
    summary: Add a new product
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductPostBodyMinimal'
          examples:
            AllInfo:
              value:
                title: { en: 'Bowl blue 750ml', ua: 'Миска синя 750мл' }
                description:
                  {
                    en: 'Bowl blue for dogs 750ml',
                    ua: 'Миска синя для собак 750мл',
                  }
                price: 750
                stars: 4
                iamge: 'http://example.com/image.png'
                category: ['638785594eb73fc2e0a4e07c']
                type: ['638785594eb73fc2e0a4e07c']
                producer: '638785594eb73fc2e0a4e07c'
                novelty: true
                discount: false
                discountValue: -1
                discountPreviousPrice: -1
                creator: '638785594eb73fc2e0a4e07c'
            Minimal:
              value:
                title: { en: 'Bowl blue 750ml', ua: 'Миска синя 750мл' }
                description:
                  {
                    en: 'Bowl blue for dogs 750ml',
                    ua: 'Миска синя для собак 750мл',
                  }
                price: 400
                stars: 5
                iamge: 'http://example.com/image.png'
                category: ['638785594eb73fc2e0a4e07c']
                type: ['638785594eb73fc2e0a4e07c']
                producer: '638785594eb73fc2e0a4e07c'
                creator: '638785594eb73fc2e0a4e07c'

    responses:
      '200':
        description: A JSON Type
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      '500':
        description: Error message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandartErrorMessage'
      '401':
        $ref: '#/components/responses/UnauthorizedError'
    security:
      - BasicAuth: []
  put:
    tags: [Product]
    summary: Update type info
    parameters:
      - in: query
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: titleEN
        schema:
          type: string
      - in: query
        name: titleUA
        schema:
          type: string
      - in: query
        name: descriptionEN
        schema:
          type: string
      - in: query
        name: descriptionUA
        schema:
          type: string
      - in: query
        name: price
        schema:
          type: number
      - in: query
        name: stars
        schema:
          type: string
      - in: query
        name: image
        schema:
          type: string
      - in: query
        name: type
        schema:
          type: array
          items:
            type: string
      - in: query
        name: category
        schema:
          type: array
          items:
            type: string
      - in: query
        name: novelty
        schema:
          type: boolean
      - in: query
        name: discount
        schema:
          type: boolean
      - in: query
        name: discountValue
        schema:
          type: number
      - in: query
        name: discountPreviousPrice
        schema:
          type: number

    responses:
      '200':
        description: A JSON Type
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      '500':
        description: Error message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandartErrorMessage'
    '401':
      $ref: '#/components/responses/UnauthorizedError'
    security:
      - BasicAuth: []

/product/{_id}:
  delete:
    tags: [Product]
    summary: Delete product
    parameters:
      - in: path
        name: _id
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: 'ok'
                  description: Status of query = OK
                message:
                  type: string
                  example: 'Type {_id} successfully deleted'
                  description: Message of success
      '500':
        description: Error message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandartErrorMessage'
      '401':
        $ref: '#/components/responses/UnauthorizedError'
    security:
      - BasicAuth: []
